"""Simulator boundary used by the worker."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol


class SimulatorAdapter(Protocol):
    def create(self, bddl: Path, config: Any, *, max_steps: int, seed: int) -> Any: ...
    def restore(self, env: Any, state: Any) -> dict[str, Any]: ...
    def observations(self, env: Any, observation: dict[str, Any]) -> dict[str, Any]: ...
    def render(self, env: Any, camera: str, width: int, height: int) -> Any: ...
    def close(self, env: Any) -> None: ...
